
import javax.swing.*;
import java.sql.*;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author 1049
 */
public class demo1 extends javax.swing.JFrame {

	/**
	 * Creates new form demo1
	 */
	Connection con;
	Statement st;
	PreparedStatement ps;
	ResultSet rs;

	public demo1() {
		initComponents();
		try {
			Class.forName("oracle.jdbc.OracleDriver");
			JOptionPane.showMessageDialog(this, "Driver Loaded!");
			try {
				con = DriverManager.getConnection("jdbc:oracle:thin:@10.6.4.33:1521:orcl", "1049", "1049");
				JOptionPane.showMessageDialog(this, "Connected to Oracle database!");
			} catch (SQLException ex) {
				Logger.getLogger(demo1.class.getName()).log(Level.SEVERE, null, ex);
				JOptionPane.showMessageDialog(this, ex.getMessage());
			}
		} catch (ClassNotFoundException ex) {
			Logger.getLogger(demo1.class.getName()).log(Level.SEVERE, null, ex);
			JOptionPane.showMessageDialog(this, ex.getMessage());
		}

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		SEX1 = new javax.swing.JLabel();
		EID = new javax.swing.JLabel();
		NAME = new javax.swing.JLabel();
		DOB = new javax.swing.JLabel();
		SEX = new javax.swing.JLabel();
		DESIGNATION = new javax.swing.JLabel();
		BASICPAY = new javax.swing.JLabel();
		name = new javax.swing.JTextField();
		eid = new javax.swing.JTextField();
		sex = new javax.swing.JTextField();
		dob = new javax.swing.JTextField();
		basic = new javax.swing.JTextField();
		designation = new javax.swing.JTextField();
		insert = new javax.swing.JButton();
		update = new javax.swing.JButton();
		delete = new javax.swing.JButton();
		refresh = new javax.swing.JButton();
		search = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		exit = new javax.swing.JButton();
		DA = new javax.swing.JLabel();
		HRA = new javax.swing.JLabel();
		PF = new javax.swing.JLabel();
		GROSS = new javax.swing.JLabel();
		TOTAL_DEDUCTION = new javax.swing.JLabel();
		NETPAY = new javax.swing.JLabel();
		da = new javax.swing.JTextField();
		hra = new javax.swing.JTextField();
		pf = new javax.swing.JTextField();
		gross = new javax.swing.JTextField();
		tot_deduc = new javax.swing.JTextField();
		net_pay = new javax.swing.JTextField();

		SEX1.setText("SEX");
		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		EID.setText("EID");

		NAME.setText("NAME");

		DOB.setText("DATE OF BIRTH");

		SEX.setText("SEX");

		DESIGNATION.setText("DESIGNATION");

		BASICPAY.setText("BASIC PAY");

		eid.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				eidActionPerformed(evt);
			}
		});

		sex.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				sexActionPerformed(evt);
			}
		});

		insert.setText("INSERT");
		insert.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				insertActionPerformed(evt);
			}
		});

		update.setText("UPDATE");
		update.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				updateActionPerformed(evt);
			}
		});

		delete.setText("DELETE");
		delete.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				deleteActionPerformed(evt);
			}
		});

		refresh.setText("REFRESH");
		refresh.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				refreshActionPerformed(evt);
			}
		});

		search.setText("SEARCH");
		search.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				searchActionPerformed(evt);
			}
		});

		jLabel1.setText("EMPLOYEE  DATABASE");

		exit.setText("EXIT");
		exit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				exitActionPerformed(evt);
			}
		});

		DA.setText("DA");

		HRA.setText("HRA");

		PF.setText("PF");

		GROSS.setText("GROSS");

		TOTAL_DEDUCTION.setText("TOTAL DEDUCTION");

		NETPAY.setText("NET PAY");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addGap(61, 61, 61)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
												.createSequentialGroup()
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(search, javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(insert, javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
												.addGap(30, 30, 30)
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(refresh, javax.swing.GroupLayout.DEFAULT_SIZE,
																152, Short.MAX_VALUE)
														.addComponent(update, javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
												.addGap(27, 27, 27)
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(delete, javax.swing.GroupLayout.DEFAULT_SIZE, 139,
																Short.MAX_VALUE)
														.addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
										.addGroup(layout.createSequentialGroup()
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(layout.createSequentialGroup()
																.addGroup(layout.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.TRAILING)
																		.addComponent(BASICPAY,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				93,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(DESIGNATION,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				93,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(SEX,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				93,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(DOB,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				93,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(NAME,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				93,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(EID,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				93,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(layout.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																		.addGroup(layout.createSequentialGroup()
																				.addGroup(layout.createParallelGroup(
																						javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(dob,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								111,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(name,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								111,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(eid,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								111,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																				.addGap(39, 39, 39)
																				.addGroup(layout.createParallelGroup(
																						javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(PF,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								84,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addGroup(layout
																								.createParallelGroup(
																										javax.swing.GroupLayout.Alignment.LEADING,
																										false)
																								.addComponent(HRA,
																										javax.swing.GroupLayout.Alignment.TRAILING,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										84,
																										Short.MAX_VALUE)
																								.addComponent(DA,
																										javax.swing.GroupLayout.Alignment.TRAILING,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										Short.MAX_VALUE))))
																		.addGroup(layout.createSequentialGroup()
																				.addGroup(layout.createParallelGroup(
																						javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(sex,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								111,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(designation,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								111,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(basic,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								111,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																				.addGap(39, 39, 39)
																				.addGroup(layout.createParallelGroup(
																						javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(NETPAY,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								84,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addGroup(layout
																								.createParallelGroup(
																										javax.swing.GroupLayout.Alignment.LEADING,
																										false)
																								.addComponent(
																										TOTAL_DEDUCTION,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										1,
																										Short.MAX_VALUE)
																								.addComponent(GROSS,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										84,
																										Short.MAX_VALUE))))))
														.addGroup(layout.createSequentialGroup()
																.addGap(176, 176, 176)
																.addComponent(jLabel1,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 124,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addGap(31, 31, 31)
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING,
																		false)
																.addComponent(hra)
																.addComponent(pf)
																.addComponent(gross)
																.addComponent(tot_deduc)
																.addComponent(net_pay,
																		javax.swing.GroupLayout.DEFAULT_SIZE, 121,
																		Short.MAX_VALUE))
														.addComponent(da, javax.swing.GroupLayout.PREFERRED_SIZE, 121,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGap(0, 0, Short.MAX_VALUE)))
								.addGap(57, 57, 57)));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(EID)
										.addComponent(eid, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(DA)
										.addComponent(da, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(12, 12, 12)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(NAME)
										.addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(HRA)
										.addComponent(hra, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(DOB, javax.swing.GroupLayout.PREFERRED_SIZE, 20,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(dob)
										.addComponent(PF)
										.addComponent(pf, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(SEX)
										.addComponent(sex, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(GROSS)
										.addComponent(gross, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(11, 11, 11)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(DESIGNATION)
										.addComponent(designation)
										.addComponent(TOTAL_DEDUCTION)
										.addComponent(tot_deduc, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(BASICPAY)
										.addComponent(basic, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(NETPAY)
										.addComponent(net_pay, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(54, 54, 54)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(insert)
										.addComponent(update)
										.addComponent(delete))
								.addGap(18, 18, 18)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(refresh)
										.addComponent(search)
										.addComponent(exit))
								.addGap(19, 19, 19)));

		pack();
	}// </editor-fold>

	private void refresh() {
		eid.setText("");
		name.setText("");
		designation.setText("");
		basic.setText("");
		dob.setText("");
		sex.setText("");
	}

	private void calcf(String eid, String basic) {
		try {
			String sql = "call calc(?,?)";
			ps = con.prepareStatement(sql);
			ps.setString(1, eid);
			ps.setString(2, basic);
			ps.execute();
		} catch (SQLException ex) {
			Logger.getLogger(demo1.class.getName()).log(Level.SEVERE, null, ex);
			JOptionPane.showMessageDialog(this, ex.getMessage());
		}
	}

	private void refreshActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:

		refresh();

	}

	private void sexActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void insertActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		try {
			String sql = "insert into emp_payroll values(?,?,?,?,?,?,NULL,NULL,NULL,NULL,NULL,NULL,NULL)";
			ps = con.prepareStatement(sql);
			ps.setString(1, eid.getText());
			ps.setString(2, name.getText());
			ps.setString(3, dob.getText());
			ps.setString(4, sex.getText());
			ps.setString(5, designation.getText());
			ps.setString(6, basic.getText());
			ps.execute();
			calcf(eid.getText(), basic.getText());
			JOptionPane.showMessageDialog(this, "Inserted!");
			refresh();
		} catch (SQLException ex) {
			Logger.getLogger(demo1.class.getName()).log(Level.SEVERE, null, ex);
			JOptionPane.showMessageDialog(this, ex.getMessage());
		}
	}

	private void deleteActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		try {
			String sql = "delete from emp_payroll where eid=?";
			ps = con.prepareStatement(sql);
			ps.setString(1, eid.getText());
			ps.execute();
			JOptionPane.showMessageDialog(this, "Deleted!");
			refresh();
		} catch (SQLException ex) {
			Logger.getLogger(demo1.class.getName()).log(Level.SEVERE, null, ex);
			JOptionPane.showMessageDialog(this, ex.getMessage());
		}
	}

	private void exitActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		System.exit(0);
	}

	private void searchActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		try {
			String sql = "select * from emp_payroll where eid = '" + eid.getText() + "'";
			st = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
			rs = st.executeQuery(sql);
			if (rs.next()) {
				eid.setText(rs.getString(1));
				name.setText(rs.getString(2));
				dob.setText(rs.getString(3));
				sex.setText(rs.getString(4));
				designation.setText(rs.getString(5));
				basic.setText(rs.getString(6));
				da.setText(rs.getString(7));
				hra.setText(rs.getString(8));
				gross.setText(rs.getString(9));
				pf.setText(rs.getString(10));
				tot_deduc.setText(rs.getString(11));
				net_pay.setText(rs.getString(12));
				// String s=rs.getString(13);
				JOptionPane.showMessageDialog(this, "Record Found!");
			} else {
				JOptionPane.showMessageDialog(this, "Record Not Found!");
			}
		} catch (SQLException ex) {
			Logger.getLogger(demo1.class.getName()).log(Level.SEVERE, null, ex);
			JOptionPane.showMessageDialog(this, ex.getMessage());
		}
	}

	private void updateActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		try {
			String sql = "update emp_payroll set ename=?,dob=?,sex=?,designation=?,basic=? where eid=?";
			ps = con.prepareStatement(sql);
			ps.setString(6, eid.getText());
			ps.setString(1, name.getText());
			ps.setString(2, dob.getText());
			ps.setString(3, sex.getText());
			ps.setString(4, designation.getText());
			ps.setString(5, basic.getText());
			ps.execute();
			calcf(eid.getText(), basic.getText());
			JOptionPane.showMessageDialog(this, "Updated!");
			refresh();
		} catch (SQLException ex) {
			Logger.getLogger(demo1.class.getName()).log(Level.SEVERE, null, ex);
			JOptionPane.showMessageDialog(this, ex.getMessage());
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel.
		 * For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(demo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(demo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(demo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(demo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new demo1().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JLabel BASICPAY;
	private javax.swing.JLabel DA;
	private javax.swing.JLabel DESIGNATION;
	private javax.swing.JLabel DOB;
	private javax.swing.JLabel EID;
	private javax.swing.JLabel GROSS;
	private javax.swing.JLabel HRA;
	private javax.swing.JLabel NAME;
	private javax.swing.JLabel NETPAY;
	private javax.swing.JLabel PF;
	private javax.swing.JLabel SEX;
	private javax.swing.JLabel SEX1;
	private javax.swing.JLabel TOTAL_DEDUCTION;
	private javax.swing.JTextField basic;
	private javax.swing.JTextField da;
	private javax.swing.JButton delete;
	private javax.swing.JTextField designation;
	private javax.swing.JTextField dob;
	private javax.swing.JTextField eid;
	private javax.swing.JButton exit;
	private javax.swing.JTextField gross;
	private javax.swing.JTextField hra;
	private javax.swing.JButton insert;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JTextField name;
	private javax.swing.JTextField net_pay;
	private javax.swing.JTextField pf;
	private javax.swing.JButton refresh;
	private javax.swing.JButton search;
	private javax.swing.JTextField sex;
	private javax.swing.JTextField tot_deduc;
	private javax.swing.JButton update;
	// End of variables declaration

	private void log(Level SEVERE, Object object, SQLException ex) {
		throw new UnsupportedOperationException("Not supported yet."); // To change body of generated methods, choose
																		// Tools | Templates.
	}
}