/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package connect;

import javax.swing.*;
import java.sql.*;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author 1029
 * 
 */
public class dbconnect extends javax.swing.JFrame {
    /**
     * Creates new form dbconnect
     */
    Connection con;
    Statement st;
    PreparedStatement ps;
    ResultSet rs;

    public dbconnect() {
        initComponents();
        try {
            Class.forName("oracle.jdbc.OracleDriver");
            JOptionPane.showMessageDialog(this, "Driver Loaded!");
            try {
                con = DriverManager.getConnection("jdbc:oracle:thin:@10.6.4.33:1521:orcl", "1029", "1029");
                JOptionPane.showMessageDialog(this, "Connected to Oracle database!");
            } catch (SQLException ex) {
                Logger.getLogger(dbconnect.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(dbconnect.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * 
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        EIDLabel = new javax.swing.JLabel();
        eid = new javax.swing.JTextField();
        insert = new javax.swing.JButton();
        dob = new javax.swing.JTextField();
        ename = new javax.swing.JTextField();
        sex = new javax.swing.JTextField();
        EnameLabel = new javax.swing.JLabel();
        DOBLabel = new javax.swing.JLabel();
        SexLabel = new javax.swing.JLabel();
        DesignationLabel = new javax.swing.JLabel();
        designation = new javax.swing.JTextField();
        BasicLabel = new javax.swing.JLabel();
        basic = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        search = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        DALabel = new javax.swing.JLabel();
        HRALabel = new javax.swing.JLabel();
        PFLabel = new javax.swing.JLabel();
        MCLabel = new javax.swing.JLabel();
        GrossLabel = new javax.swing.JLabel();
        Tot_Deduc_Label = new javax.swing.JLabel();
        tot_deduc = new javax.swing.JTextField();
        gross = new javax.swing.JTextField();
        mc = new javax.swing.JTextField();
        pf = new javax.swing.JTextField();
        hra = new javax.swing.JTextField();
        da = new javax.swing.JTextField();
        NetPayLabel = new javax.swing.JLabel();
        net_pay = new javax.swing.JTextField();

        heading = new javax.swing.JLabel();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        EIDLabel.setText("EID");
        eid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eidActionPerformed(evt);
            }
        });
        insert.setText("Insert");
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });
        dob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobActionPerformed(evt);
            }
        });
        ename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enameActionPerformed(evt);
            }
        });
        sex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexActionPerformed(evt);

            }
        });
        EnameLabel.setText("Ename");
        DOBLabel.setText("DOB");
        SexLabel.setText("Sex");
        DesignationLabel.setText("Designation");
        designation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                designationActionPerformed(evt);
            }
        });
        BasicLabel.setText("Basic");
        basic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basicActionPerformed(evt);
            }
        });
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {

                searchActionPerformed(evt);
            }
        });
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        DALabel.setText("DA");
        HRALabel.setText("HRA");
        PFLabel.setText("PF");
        MCLabel.setText("MC");
        GrossLabel.setText("Gross");
        Tot_Deduc_Label.setText("Tot_Deduc");

        tot_deduc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tot_deducActionPerformed(evt);
            }
        });
        gross.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grossActionPerformed(evt);
            }
        });
        mc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcActionPerformed(evt);
            }
        });
        pf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfActionPerformed(evt);
            }
        });
        hra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hraActionPerformed(evt);
            }
        });
        da.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daActionPerformed(evt);

            }
        });
        NetPayLabel.setText("Net Pay");
        net_pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                net_payActionPerformed(evt);
            }
        });
        heading.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        heading.setText("EMP_PAYROLL DATABASE");
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                layout.createSequentialGroup()
                                        .addContainerGap(29, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                        layout.createSequentialGroup()
                                                                .addComponent(pf,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 62,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()

                                                                                .addComponent(net_pay,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        62,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addContainerGap())
                                                                        .addGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                layout.createSequentialGroup()
                                                                                        .addComponent(NetPayLabel)
                                                                                        .addGap(22, 22, 22))))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                        layout.createSequentialGroup()
                                                                .addComponent(insert)
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(exit)
                                                                                .addGap(81, 81, 81)
                                                                                .addComponent(clear))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(13, 13, 13)
                                                                                .addComponent(update)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(delete)
                                                                                .addGap(26, 26, 26)
                                                                                .addComponent(search)))
                                                                .addGap(41, 41, 41))))
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(DOBLabel)
                                                        .addComponent(EnameLabel)

                                                        .addComponent(EIDLabel))
                                                .addGap(42, 42, 42)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(eid,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 62,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(dob,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 62,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(ename,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 62,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(DesignationLabel)
                                                        .addComponent(BasicLabel)
                                                        .addComponent(SexLabel))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(sex,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 62,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(basic,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 62,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(designation,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 62,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Tot_Deduc_Label)
                                        .addComponent(GrossLabel)

                                        .addComponent(MCLabel)
                                        .addComponent(PFLabel)
                                        .addComponent(HRALabel)
                                        .addComponent(DALabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(da,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 62,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(hra,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 62,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(mc,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 62,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(gross,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 62,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(tot_deduc,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 62,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(heading)
                                .addGap(0, 0, Short.MAX_VALUE)));
        layout.setVerticalGroup(

                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(heading)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(EIDLabel)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(eid,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(DALabel)
                                                .addComponent(da,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(EnameLabel)
                                        .addComponent(ename,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(HRALabel)
                                        .addComponent(hra,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)

                                        .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(DOBLabel)
                                                        .addComponent(dob,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(PFLabel)
                                                        .addComponent(pf,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        15, Short.MAX_VALUE)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(SexLabel)
                                                        .addComponent(sex,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(MCLabel)
                                                        .addComponent(mc,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(designation,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,

                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(DesignationLabel)
                                                        .addComponent(GrossLabel)
                                                        .addComponent(gross,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(basic,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(BasicLabel))
                                                        .addGroup(layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(Tot_Deduc_Label)
                                                                .addComponent(tot_deduc,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(18, 18, 18))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addComponent(NetPayLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(net_pay,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)

                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(update)
                                        .addComponent(insert)
                                        .addComponent(delete)
                                        .addComponent(search))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(exit)
                                        .addComponent(clear))
                                .addContainerGap()));
        pack();
    }// </editor-fold>

    private void cleartext() {
        eid.setText("");
        ename.setText("");
        dob.setText("");
        sex.setText("");
        designation.setText("");
        basic.setText("");
        da.setText("");
        hra.setText("");
        pf.setText("");
        mc.setText("");
        gross.setText("");
        tot_deduc.setText("");
        net_pay.setText("");
    }

    private void setAll(String eid, String basic) {
        try {
            String sql = "call calcpay(?,?)";
            ps = con.prepareStatement(sql);

            ps.setString(1, eid);
            ps.setString(2, basic);
            ps.execute();
        } catch (SQLException ex) {
            Logger.getLogger(dbconnect.class.getName()).log(Level.SEVERE,
                    null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    private void eidActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

private void insertActionPerformed(java.awt.event.ActionEvent evt)
{
try {
String sql = "insert into emp_payroll
values(?,?,?,?,?,?,null,null,null,null,null,null,null)";
ps = con.prepareStatement(sql);
ps.setString(1, eid.getText());
ps.setString(2, ename.getText());
ps.setString(3, dob.getText());
ps.setString(4, sex.getText());
ps.setString(5, designation.getText());
ps.setString(6, basic.getText());
ps.execute();
setAll(eid.getText(),basic.getText());
JOptionPane.showMessageDialog(this,"Inserted!");
cleartext();
}
catch (SQLException ex) {
Logger.getLogger(dbconnect.class.getName()).log(Level.SEVERE,
null, ex);
JOptionPane.showMessageDialog(this,ex.getMessage());
}
}

    private void dobActionPerformed(java.awt.event.ActionEvent evt) {

        // TODO add your handling code here:
    }

    private void enameActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void sexActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void designationActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void basicActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

private void updateActionPerformed(java.awt.event.ActionEvent evt)
{
// TODO add your handling code here:
try{
String sql = "update emp_payroll set
ename=?,dob=?,sex=?,designation=?,basic=? where eid=?";
ps = con.prepareStatement(sql);
ps.setString(6, eid.getText());
ps.setString(1, ename.getText());
ps.setString(2, dob.getText());
ps.setString(3, sex.getText());
ps.setString(4, designation.getText());
ps.setString(5, basic.getText());
ps.execute();
setAll(eid.getText(),basic.getText());
JOptionPane.showMessageDialog(this, "Updated!");
cleartext();
}

catch (SQLException ex) {
Logger.getLogger(dbconnect.class.getName()).log(Level.SEVERE, null,
ex);
JOptionPane.showMessageDialog(this,ex.getMessage());
}
}

private void searchActionPerformed(java.awt.event.ActionEvent evt)
{
// TODO add your handling code here:
try {
// TODO add your handling code here:
String sql = "select * from emp_payroll where eid =
'"+eid.getText()+"'";
st =
con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_U
PDATABLE);
rs = st.executeQuery(sql);
if(rs.next()){
eid.setText(rs.getString(1));
ename.setText(rs.getString(2));
dob.setText(rs.getString(3));
sex.setText(rs.getString(4));
designation.setText(rs.getString(5));
basic.setText(rs.getString(6));
da.setText(rs.getString(7));
hra.setText(rs.getString(8));
pf.setText(rs.getString(9));
mc.setText(rs.getString(10));
gross.setText(rs.getString(11));
tot_deduc.setText(rs.getString(12));
net_pay.setText(rs.getString(13));
JOptionPane.showMessageDialog(this, "Record Found!");
}
else
JOptionPane.showMessageDialog(this, "Record Not Found!");
}
catch (SQLException ex) {
Logger.getLogger(dbconnect.class.getName()).log(Level.SEVERE, null,
ex);

JOptionPane.showMessageDialog(this, ex.getMessage());
}
}

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        try {
            String sql = "delete from emp_payroll where eid=?";
            ps = con.prepareStatement(sql);
            ps.setString(1, eid.getText());
            ps.execute();
            JOptionPane.showMessageDialog(this, "Deleted!");
            cleartext();
        } catch (SQLException ex) {
            Logger.getLogger(dbconnect.class.getName()).log(Level.SEVERE, null,
                    ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        System.exit(0);
    }

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        cleartext();
    }

    private void tot_deducActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void grossActionPerformed(java.awt.event.ActionEvent evt) {

        // TODO add your handling code here:
    }

    private void mcActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void pfActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void hraActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void daActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void net_payActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

/**
* @param args the command line arguments
*/
public static void main(String args[]) {
/* Set the Nimbus look and feel */
//<editor-fold defaultstate="collapsed" desc=" Look and feel
setting code (optional) ">
/* If Nimbus (introduced in Java SE 6) is not available, stay
with the default look and feel.
* For details see
http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.ht
ml
*/
try {
for (javax.swing.UIManager.LookAndFeelInfo info :
javax.swing.UIManager.getInstalledLookAndFeels()) {

if ("Nimbus".equals(info.getName())) {
javax.swing.UIManager.setLookAndFeel(info.getClassName());
break;
}
}
} catch (ClassNotFoundException ex) {
java.util.logging.Logger.getLogger(dbconnect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
} catch (InstantiationException ex) {
java.util.logging.Logger.getLogger(dbconnect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
} catch (IllegalAccessException ex) {
java.util.logging.Logger.getLogger(dbconnect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
} catch (javax.swing.UnsupportedLookAndFeelException ex) {
java.util.logging.Logger.getLogger(dbconnect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
}
//</editor-fold>
/* Create and display the form */
java.awt.EventQueue.invokeLater(new Runnable() {
public void run() {
new dbconnect().setVisible(true);
}
});
}

    // Variables declaration - do not modify
    private javax.swing.JLabel BasicLabel;
    private javax.swing.JLabel DALabel;
    private javax.swing.JLabel DOBLabel;
    private javax.swing.JLabel DesignationLabel;
    private javax.swing.JLabel EIDLabel;
    private javax.swing.JLabel EnameLabel;

    private javax.swing.JLabel GrossLabel;
    private javax.swing.JLabel HRALabel;
    private javax.swing.JLabel MCLabel;
    private javax.swing.JLabel NetPayLabel;
    private javax.swing.JLabel PFLabel;
    private javax.swing.JLabel SexLabel;
    private javax.swing.JLabel Tot_Deduc_Label;
    private javax.swing.JTextField basic;
    private javax.swing.JButton clear;
    private javax.swing.JTextField da;
    private javax.swing.JButton delete;
    private javax.swing.JTextField designation;
    private javax.swing.JTextField dob;
    private javax.swing.JTextField eid;
    private javax.swing.JTextField ename;
    private javax.swing.JButton exit;
    private javax.swing.JTextField gross;
    private javax.swing.JLabel heading;
    private javax.swing.JTextField hra;
    private javax.swing.JButton insert;
    private javax.swing.JTextField mc;
    private javax.swing.JTextField net_pay;
    private javax.swing.JTextField pf;
    private javax.swing.JButton search;
    private javax.swing.JTextField sex;
    private javax.swing.JTextField tot_deduc;
    private javax.swing.JButton update;
    // End of variables declaration
}