CREATE TABLE EMP_PAYROLL(
    EID VARCHAR(5) PRIMARY KEY,
	ENAME VARCHAR(10), 
	DOB DATE, 
	SEX VARCHAR(1), 
	DESIGNATION VARCHAR(10), 
	BASIC NUMBER, 
	DA NUMBER, 
	HRA NUMBER, 
	PF NUMBER, 
	MC NUMBER, 
	GROSS NUMBER, 
	TOT_DEDUC NUMBER,
	NET_PAY NUMBER
);



CREATE OR REPLACE TRIGGER BEFORE_EMP_PAYROLL_INSERT
BEFORE INSERT ON EMP_PAYROLL FOR EACH ROW
DECLARE 
	BBASIC NUMBER:=:NEW.BASIC;
BEGIN
    :NEW.DA:=0.6*BBASIC;
	:NEW.HRA:=0.11*BBASIC;
	:NEW.PF:=0.04*BBASIC;
	:NEW.MC:=0.03*BBASIC;
	:NEW.GROSS:=BBASIC+:NEW.DA+:NEW.HRA;
	:NEW.TOT_DEDUC:=:NEW.PF+:NEW.MC;
	:NEW.NET_PAY:=:NEW.GROSS-:NEW.TOT_DEDUC;
END;
/


CREATE OR REPLACE PROCEDURE CALC
(ID IN EMP_PAYROLL.EID%TYPE, BASIC IN EMP_PAYROLL.BASIC%TYPE)
IS
DA1 NUMBER;
HRA1 NUMBER;
PF1 NUMBER;
MC1 NUMBER;
GROSS1 NUMBER;
TOT_DEDUC1 NUMBER;
NET_PAY1 NUMBER;
BEGIN
DA1:=0.6*BASIC;
HRA1:=0.11*BASIC;
PF1:=0.04*BASIC;
MC1:=0.03*BASIC;
GROSS1:=BASIC+DA1+HRA1;
TOT_DEDUC1:=PF1+MC1;
NET_PAY1:=GROSS1-TOT_DEDUC1;
UPDATE EMP_PAYROLL
SET DA=DA1, HRA=HRA1, PF=PF1, MC=MC1, GROSS=GROSS1,
TOT_DEDUC=TOT_DEDUC1, NET_PAY=NET_PAY1
WHERE EID=ID;
END;
/

create table emp_payroll (
eid varchar2(4) constraint emp_payroll_pk PRIMARY KEY,
name varchar2(20),
dob date,
sex varchar2(6) constraint emp_ch_sex CHECK (sex in ('MALE','FEMALE')),
designation varchar2(15),
bp number,
da number,
hra number,
pf number,
mc number,
gross number,
tot_deduc number,
net_pay number
);

CREATE OR REPLACE PROCEDURE CALC
(ID IN EMP_PAYROLL.EID%TYPE, BASIC IN EMP_PAYROLL.BASIC%TYPE)
IS
	DA_TEMP NUMBER;
	HRA_TEMP NUMBER;
	PF_TEMP NUMBER;
	MC_TEMP NUMBER;
	GROSS_TEMP NUMBER;
	TOT_DEDUC_TEMP NUMBER;
	NET_PAY_TEMP NUMBER;
BEGIN
	DA_TEMP:=0.6*BASIC;
	HRA_TEMP:=0.11*BASIC;
	PF_TEMP:=0.04*BASIC;
	MC_TEMP:=0.03*BASIC;
	GROSS_TEMP:=BASIC+DA_TEMP+HRA_TEMP;
	TOT_DEDUC_TEMP:=PF_TEMP+MC_TEMP;
	NET_PAY_TEMP:=GROSS_TEMP-TOT_DEDUC_TEMP;
	UPDATE EMP_PAYROLL
	SET DA=DA_TEMP, HRA=HRA_TEMP, PF=PF_TEMP, MC=MC_TEMP, GROSS=GROSS_TEMP,
	TOT_DEDUC=TOT_DEDUC_TEMP, NET_PAY=NET_PAY_TEMP
	WHERE EID=ID;
END;
/




SQL> CREATE TABLE EMP_PAYROLL(
  2      EID VARCHAR(5) PRIMARY KEY,
  3  ENAME VARCHAR(10),
  4  DOB DATE,
  5  SEX VARCHAR(1),
  6  DESIGNATION VARCHAR(10),
  7  BASIC NUMBER,
  8  DA NUMBER,
  9  HRA NUMBER,
 10  PF NUMBER,
 11  MC NUMBER,
 12  GROSS NUMBER,
 13  TOT_DEDUC NUMBER,
 14  NET_PAY NUMBER
 15  );

Table created.


SQL> CREATE OR REPLACE PROCEDURE CALC
  2  (ID IN EMP_PAYROLL.EID%TYPE, BASIC IN EMP_PAYROLL.BASIC%TYPE)
  3  IS
  4  DA_TEMP NUMBER;
  5  HRA_TEMP NUMBER;
  6  PF_TEMP NUMBER;
  7  MC_TEMP NUMBER;
  8  GROSS_TEMP NUMBER;
  9  TOT_DEDUC_TEMP NUMBER;
 10  NET_PAY_TEMP NUMBER;
 11  BEGIN
 12  DA_TEMP:=0.6*BASIC;
 13  HRA_TEMP:=0.11*BASIC;
 14  PF_TEMP:=0.04*BASIC;
 15  MC_TEMP:=0.03*BASIC;
 16  GROSS_TEMP:=BASIC+DA_TEMP+HRA_TEMP;
 17  TOT_DEDUC_TEMP:=PF_TEMP+MC_TEMP;
 18  NET_PAY_TEMP:=GROSS_TEMP-TOT_DEDUC_TEMP;
 19  UPDATE EMP_PAYROLL
 20  SET DA=DA_TEMP, HRA=HRA_TEMP, PF=PF_TEMP, MC=MC_TEMP, GROSS=GROSS_TEMP,
 21  TOT_DEDUC=TOT_DEDUC_TEMP, NET_PAY=NET_PAY_TEMP
 22  WHERE EID=ID;
 23  END;
 24  /

Procedure created.

