SET SERVEROUTPUT ON;

DECLARE
FOODFLAVOR PRODUCTS%ROWTYPE;
FOODSS PRODUCTS%ROWTYPE;
FLAG INTEGER;
FOOD_SEARCH PRODUCTS.FOOD%TYPE;
FLAVOR_SEARCH PRODUCTS.FLAVOR%TYPE;

-- CURSOR C1(FOOD_SEARCH IN PRODUCTS.FOOD%TYPE) IS SELECT * INTO FOODFLAVOR FROM PRODUCTS WHERE FOOD=FOOD_SEARCH; 
-- CURSOR C2(FLAVOR_SEARCH IN PRODUCTS.FLAVOR%TYPE) IS SELECT * INTO FOODFLAVOR FROM PRODUCTS WHERE FLAVOR=FLAVOR_SEARCH; 
BEGIN
	FOOD_SEARCH:='&FOOD_TYPE_SEARCH';
	FLAVOR_SEARCH:='&FLAVOR_TYPE_SEARCH';
	SELECT * INTO FOODFLAVOR FROM PRODUCTS WHERE FOOD=FOOD_SEARCH AND FLAVOR=FLAVOR_SEARCH;
	DBMS_OUTPUT.PUT_LINE('THE COMBINATION YOU ASKED FOR IS LISTED BELOW :');
	DBMS_OUTPUT.PUT_LINE(FOODFLAVOR.PID||' '||FOODFLAVOR.FLAVOR||' '||FOODFLAVOR.FOOD||' '||FOODFLAVOR.PRICE);
	FLAG:=1;

	-- IF FLAG=0 THEN
	-- 	SELECT * INTO FOODSS FROM PRODUCTS WHERE FOOD=FOOD_SEARCH;
    -- 	DBMS_OUTPUT.PUT_LINE('THE FOOD YOU ASKED FOR IS AVAILABLE IN OTHER FLAVORS');
        -- EXCEPTION
        -- WHEN NO_DATA_FOUND THEN
        --     DBMS_OUTPUT.PUT_LINE('THE FOOD YOU ASKED FOR IS NOT AVAILABLE');

        -- SELECT * INTO FOODFLAVOR FROM PRODUCTS WHERE FLAVOR=FLAVOR_SEARCH;
        -- EXCEPTION
        -- WHEN NO_DATA_FOUND THEN
        --     DBMS_OUTPUT.PUT_LINE('THE FOOD YOU ASKED FOR IS NOT AVAILABLE');

	EXCEPTION
    WHEN NO_DATA_FOUND THEN
		FLAG:=0;
    	DBMS_OUTPUT.PUT_LINE('THE COMBINATION YOU ASKED FOR IS NOT AVAILABLE');

END;
/