--  DROPPING ALL TABLES
DROP TABLE ITEM_LIST;

DROP TABLE RECEIPTS;

DROP TABLE PRODUCTS;

DROP TABLE CUSTOMERS;

--  CREATING CUSTOMERS TABLE
CREATE TABLE CUSTOMERS (
    CID NUMBER CONSTRAINT CUSID_PKEY PRIMARY KEY,
    FNAME VARCHAR2(30),
    LNAME VARCHAR2(30)
);

--  DISPLAYING THE ATTRIBUTES AND THEIR DATA TYPES OF THE CUSTOMERS TABLE
DESC CUSTOMERS;

--  CREATING PRODUCTS TABLE
CREATE TABLE PRODUCTS (
    PID VARCHAR2(15) CONSTRAINT PRODUCTS_PKEY PRIMARY KEY,
    FLAVOR VARCHAR2(20),
    FOOD VARCHAR2(20),
    PRICE NUMBER
);

--  DISPLAYING THE ATTRIBUTES AND THEIR DATA TYPES OF THE PRODUCTS TABLE
DESC PRODUCTS;

--  CREATING RECEIPTS TABLE
CREATE TABLE RECEIPTS (
    RNO NUMBER CONSTRAINT RNO_PKEY PRIMARY KEY,
    RDATE DATE,
    CID NUMBER CONSTRAINT CUSID_FORKEY REFERENCES CUSTOMERS(CID)
);

--  DISPLAYING THE ATTRIBUTES AND THEIR DATA TYPES OF THE RECEIPTS TABLE
DESC RECEIPTS;

--  CREATING TABLE ITEM_LIST
CREATE TABLE ITEM_LIST (
    RNO NUMBER CONSTRAINT RECEIPTNO_FORKEY REFERENCES RECEIPTS(RNO),
    ORDINAL NUMBER CONSTRAINT ITEM_CHK CHECK(ORDINAL != 0),
    ITEM VARCHAR2(15) CONSTRAINT PID_FORKEY REFERENCES PRODUCTS(PID),
    CONSTRAINT ITEM_LIST_FORKEY PRIMARY KEY(RNO, ORDINAL)
);

--  DISPLAYING THE ATTRIBUTES AND THEIR DATA TYPES OF THE ITEM_LIST TABLE
DESC ITEM_LIST;