CREATE OR REPLACE FUNCTION MOST_CUST BUDGETFOODFN
(BUDGET IN NUMBER,FOODTYPE IN PRODUCTS.FOOD%TYPE)
RETURN number
AS
    CURSOR C1 IS SELECT PID,FOOD,FLAVOR,PRICE FROM PRODUCTS WHERE FOOD=FOODTYPE AND PRICE<BUDGET;
    PRODUCTROW C1%ROWTYPE;
    CNT NUMBER:=0;
    FLAG NUMBER:=0;
    PIID ITEM_LIST.ITEM%TYPE;
    FLAVOR PRODUCTS.FLAVOR%TYPE;
    productprice PRODUCTS.PRICE%TYPE;
    ITEMSINBAG NUMBER;

BEGIN
    DBMS_OUTPUT.PUT_LINE('BUDGET:'||BUDGET||'    '||'FOOD:'||FOODTYPE);
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('ITEM ID    FOOD    FLAVOR    PRICE');
    OPEN C1;
    LOOP
        FETCH C1 INTO PRODUCTROW;
        IF C1%NOTFOUND THEN
            EXIT;
        END IF;
        SELECT COUNT(*) INTO FLAG FROM ITEM_LIST WHERE ITEM=PRODUCTROW.PID;
        IF FLAG>CNT THEN
            CNT:=FLAG;
            PIID:=PRODUCTROW.PID;

        END IF;
        DBMS_OUTPUT.PUT_LINE(PRODUCTROW.PID||'    '||PRODUCTROW.FOOD||'    '||PRODUCTROW.FLAVOR||'    '||PRODUCTROW.PRICE);
    END LOOP;
    CLOSE C1;
    SELECT FLAVOR INTO FLAVOR FROM PRODUCTS WHERE PID=PIID;
    SELECT PRICE INTO productprice FROM PRODUCTS WHERE PID=PIID;
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('THE ITEM WITH ID '||PIID||' AND '||FLAVOR||' IS THE BEST CHOICE FOR YOU');
    ITEMSINBAG:=BUDGET/productprice;
    DBMS_OUTPUT.PUT_LINE('YOU CAN BUY A MAXIMUM OF '||ITEMSINBAG||' ITEM OF THIS PRODUCT');
    DBMS_OUTPUT.PUT_LINE('');
END;
/
