-- REM ***DROPPING TABLES***
DROP TABLE ORDER_CONTENTS;

DROP TABLE ORDERS;

DROP TABLE PARTS;

DROP TABLE CUSTOMER;

DROP TABLE EMPLOYEE;

-- REM ***CREATING TABLE EMPLOYEE***
CREATE TABLE EMPLOYEE(
    EMP_NO VARCHAR(5) CONSTRAINT E_PRIMEKEY PRIMARY KEY,
    ENAME VARCHAR(20),
    DOB DATE,
    PINCODE INT,
    CITY VARCHAR(20),
    CONSTRAINT ESTART_LETTER CHECK(EMP_NO LIKE 'E%')
);

DESC EMPLOYEE;

-- REM ***INSERTING VALUES INTO EMPLOYEE***
INSERT INTO
    EMPLOYEE
VALUES
    ('E01', 'Tony', '05-DEC-1992', 601101, 'Chennai');

INSERT INTO
    EMPLOYEE
VALUES
    ('E02', 'Steve', '23-MAR-1989', 601050, 'Madurai');

INSERT INTO
    EMPLOYEE
VALUES
    ('E03', 'Peter', '17-JUN-1995', 601302, 'Trichy');

INSERT INTO
    EMPLOYEE
VALUES
    ('E04', 'Chris', '07-JAN-1985', 601023, 'Kovai');

-- REM ***check constraint ESTART_LETTER***
INSERT INTO
    Employee
VALUES
    ('03', 'Roshan', '29/MAR/2022', 600006, 'trichy');

-- REM ***CREATING TABLE CUSTOMER***
CREATE TABLE CUSTOMER(
    CUST_NO VARCHAR(5) CONSTRAINT C_PRIMEKEY PRIMARY KEY,
    CNAME VARCHAR(20),
    STREET VARCHAR(20),
    PINCODE INT,
    CITY VARCHAR(20),
    DOB DATE,
    PHONE VARCHAR(11) CONSTRAINT PHONE_UNIQUE UNIQUE,
    CONSTRAINT CSTART_LETTER CHECK(CUST_NO LIKE 'C%')
);

DESC CUSTOMER;

-- REM ***INSERTING VALUES INTO CUSTOMER***
INSERT INTO
    CUSTOMER
VALUES
    (
        'C01',
        'Sam',
        'Street1',
        501101,
        'Delhi',
        '20-Jul-1999',
        9673125647
    );

INSERT INTO
    CUSTOMER
VALUES
    (
        'C02',
        'Shyam',
        'Street2',
        501060,
        'Mumbai',
        '19-Oct-1979',
        9670005647
    );

INSERT INTO
    CUSTOMER
VALUES
    (
        'C03',
        'Stark',
        'Street3',
        501101,
        'Kolkata',
        '20-Jul-1999',
        9848949218
    );

INSERT INTO
    CUSTOMER
VALUES
    (
        'C04',
        'Gwen',
        'Street4',
        501101,
        'Hyderabad',
        '20-Jul-1999',
        9676489841
    );

-- REM ***check constraint C_PRIMEKEY***
INSERT INTO
    CUSTOMER
VALUES
    (
        'C03',
        'Te',
        'Street',
        620265,
        'Madurai',
        '30/JUL/2022',
        9998865646
    );

-- REM ***check constraint CSTART_LETTER***
INSERT INTO
    CUSTOMER
VALUES
    (
        '04',
        'Tem',
        'Street',
        620275,
        'pondicherry',
        '30/JUL/2022',
        999866546
    );

-- REM ***CREATING TABLE PARTS***
CREATE TABLE PARTS(
    PART_NO VARCHAR(5) CONSTRAINT P_PRIMEKEY PRIMARY KEY,
    PNAME VARCHAR(20),
    PRICE INT CONSTRAINT PRICENOTNULL NOT NULL,
    QTY INT,
    CONSTRAINT QTY_MORE CHECK(QTY > 0),
    CONSTRAINT PSTART_LETTER CHECK(PART_NO LIKE 'P%')
);

DESC PARTS;

-- REM ***INSERTING VALUES INTO PARTS***
INSERT INTO
    PARTS
VALUES
    ('P01', 'Screw', 70, 1000);

INSERT INTO
    PARTS
VALUES
    ('P02', 'Pipe', 50, 1500);

INSERT INTO
    PARTS
VALUES
    ('P03', 'Wire', 10, 1200);

INSERT INTO
    PARTS
VALUES
    ('P04', 'Wood', 90, 1100);

-- REM ***check constraint PSTART_LETTER***
INSERT INTO
    PARTS
VALUES
    ('01', 'ABD', 2500, 25);

-- REM ***check constraint P_PRIMEKEY***
INSERT INTO
    PARTS
VALUES
    ('P04', 'ABD', 2500, 25);

-- REM ***CREATING TABLE ORDERS***
CREATE TABLE ORDERS(
    ORDER_NO VARCHAR(5) CONSTRAINT O_PRIMEKEY PRIMARY KEY,
    CUST_NO VARCHAR(5),
    EMP_NO VARCHAR(5),
    ORDERED DATE,
    SHIPPED DATE,
    CONSTRAINT DATE_CHECK CHECK(SHIPPED > ORDERED),
    CONSTRAINT OSTART_LETTER CHECK(ORDER_NO LIKE 'O%'),
    CONSTRAINT FORKEYEMP FOREIGN KEY(EMP_NO) REFERENCES EMPLOYEE(EMP_NO),
    CONSTRAINT FORKEYCUS FOREIGN KEY(CUST_NO) REFERENCES CUSTOMER(CUST_NO)
);

DESC ORDERS;

-- REM ***INSERTING VALUES INTO ORDERS***
INSERT INTO
    ORDERS
VALUES
    ('O01', 'C01', 'E02', '26-Jan-2022', '3-Feb-2022');

INSERT INTO
    ORDERS
VALUES
    ('O02', 'C03', 'E01', '29-Jan-2022', '8-Feb-2022');

INSERT INTO
    ORDERS
VALUES
    ('O03', 'C02', 'E04', '8-Feb-2022', '19-Feb-2022');

INSERT INTO
    ORDERS
VALUES
    (
        'O04',
        'C04',
        'E03',
        '13-Jan-2022',
        '24-Jan-2022'
    );

-- REM ***check constraint O_PRIMEKEY***
INSERT INTO
    Orders
VALUES
(
        'O03',
        'C02',
        'E03',
        '12/JAN/2022',
        '24/JAN/2022'
    );

-- REM ***check constraint DATE_CHECK***
INSERT INTO
    Orders
VALUES
(
        'O04',
        'C04',
        'E03',
        '12/JAN/2022',
        '10/JAN/2022'
    );

-- REM ***check constraint FOREIGN KEYS***
INSERT INTO
    ORDERS
VALUES
    (
        'O05',
        'C00',
        'E03',
        '13-Jan-2022',
        '24-Jan-2022'
    );

INSERT INTO
    ORDERS
VALUES
    (
        'O05',
        'C01',
        'E00',
        '13-Jan-2022',
        '24-Jan-2022'
    );

-- REM ***CREATING TABLE ORDER_CONTENTS***
CREATE TABLE ORDER_CONTENTS(
    ORDER_NO VARCHAR(5),
    PART_NO VARCHAR(5),
    QTY INT,
    CONSTRAINT FORKEYORD FOREIGN KEY(ORDER_NO) REFERENCES ORDERS(ORDER_NO),
    CONSTRAINT FORKEYPART FOREIGN KEY(PART_NO) REFERENCES PARTS(PART_NO),
    CONSTRAINT ORDERCONTENTSPRIME PRIMARY KEY(ORDER_NO, PART_NO)
);

DESC ORDER_CONTENTS;

-- REM ***INSERTING VALUES INTO ORDER_CONTENTS***
INSERT INTO
    ORDER_CONTENTS
VALUES
    ('O01', 'P02', 50);

INSERT INTO
    ORDER_CONTENTS
VALUES
    ('O03', 'P01', 45);

INSERT INTO
    ORDER_CONTENTS
VALUES
    ('O02', 'P04', 55);

INSERT INTO
    ORDER_CONTENTS
VALUES
    ('O01', 'P03', 78);

INSERT INTO
    ORDER_CONTENTS
VALUES
    ('O04', 'P02', 25);

-- REM ***check constraint FOREIGN KEYS***
INSERT INTO
    ORDER_CONTENTS
VALUES
('O03', 'P001', 4);

INSERT INTO
    ORDER_CONTENTS
VALUES
('O00', 'P04', 4);

-- REM ***ADDING REORDER_LEVEL IN PARTS*** ALTER TABLE PARTS ADD REORDER_LEVEL INT;
-- REM ***ADDING HIRE_DATE IN EMPLOYEE*** ALTER TABLE EMPLOYEE ADD HIRE_DATE DATE;
-- REM ***MODIFYING SIZE OF ENAME IN CUSTOMER*** ALTER TABLE CUSTOMER MODIFY (CNAME VARCHAR(25));
-- REM ***DELETING DOB IN CUSTOMER*** ALTER TABLE CUSTOMER
DROP COLUMN DOB;

-- REM ***MODIFYING SHIPPED NOT NULL IN ORDERS*** ALTER TABLE ORDERS MODIFY (SHIPPED DATE CONSTRAINT RECIEVENOTNULL NOT NULL);
-- REM ***CASCADING*** ALTER TABLE ORDER_CONTENTS
DROP CONSTRAINT FORKEYORD;

ALTER TABLE
    ORDER_CONTENTS
ADD
    CONSTRAINT FORKEYORD FOREIGN KEY(ORDER_NO) REFERENCES ORDERS(ORDER_NO) ON
DELETE CASCADE;

-- REM ***VIEW TABLES***
SELECT
    *
FROM
    employee;

SELECT
    *
FROM
    customer;

SELECT
    *
FROM
    parts;

SELECT
    *
FROM
    orders;

SELECT
    *
FROM
    order_contents;

-- REM ***CHECKING
ON
DELETE CASCADE * * *
DELETE FROM
    ORDERS
WHERE
    ORDER_NO = 'O01';

SELECT
    *
FROM
    orders;

SELECT
    *
FROM
    order_contents;