-- 
DROPPING TABLES

DROP TABLE ORDER_CONTENTS;
DROP TABLE ORDERS;
DROP TABLE PARTS;
DROP TABLE CUSTOMER;
DROP TABLE EMPLOYEE;

--  CREATING TABLE EMPLOYEE
CREATE TABLE EMPLOYEE
(
    ENO VARCHAR(5) CONSTRAINT PK_EMPLOYEE PRIMARY KEY,
    ENAME VARCHAR(15),
    DOB DATE,
    PINCODE NUMBER(6),
    CITY VARCHAR(15),
    CONSTRAINT ENO_START CHECK(ENO LIKE 'E%')
);

--  CREATING TABLE CUSTOMER
CREATE TABLE CUSTOMER
(
    CNO VARCHAR(5) CONSTRAINT PK_CUSTOMER PRIMARY KEY,
    CNAME VARCHAR(15),
    STREET VARCHAR(8),
    PINCODE NUMBER(6),
    CITY VARCHAR(15),
    DOB DATE,
    PHONENUMBER NUMBER(11) CONSTRAINT PHONE_UNIQUE UNIQUE,
    CONSTRAINT CNO_START CHECK(CNO LIKE 'C%')
);

--  CREATING TABLE PARTS
CREATE TABLE PARTS
(
    PNO VARCHAR(5),
    PNAME VARCHAR(8),
    PRICE NUMBER(5) CONSTRAINT PRICENOTNULL NOT NULL,
    QUANTITY NUMBER(5)
);
--  CREATING TABLE ORDERS
CREATE TABLE ORDERS
(
    ONO VARCHAR(5),
    ENO VARCHAR(5),
    CNO VARCHAR(5),
    REC_DATE DATE,
    SHIP_DATE DATE,
    CONSTRAINT DATE_ORDER CHECK(REC_DATE<SHIP_DATE),
    CONSTRAINT ONO_START CHECK(ONO LIKE 'O%'),
    CONSTRAINT FK_ORDER_EMP FOREIGN KEY(ENO) REFERENCES EMPLOYEE(ENO),
    CONSTRAINT FK_ORDER_CUS FOREIGN KEY(CNO) REFERENCES CUSTOMER(CNO)
);
--  CREATING TABLE ORDER_CONTENTS
CREATE TABLE ORDER_CONTENTS
(
    ONO VARCHAR(5),
    PNO VARCHAR(5),
    ITEM NUMBER(5),
    CONSTRAINT ITEM_NOT_ZERO CHECK (ITEM>0),
    CONSTRAINT FK_ORDERCONTENT_ONO FOREIGN KEY(ONO) REFERENCES ORDERS(ONO),
    CONSTRAINT FK_ORDERCONTENT_PNO FOREIGN KEY(PNO) REFERENCES PARTS(PNO)
);

ALTER TABLE PARTS
ADD REORDER_LEVEL INT;

ALTER TABLE EMPLOYEE
ADD HIREDATE DATE;

ALTER TABLE CUSTOMER
MODIFY
(
    CNAME VARCAHR
(25)
);

ALTER TABLE CUSTOMER
DROP COLUMN DOB;

ALTER TABLE ORDERS
ADD CONSTRAINT RECEIVED_NN NOT NULL
(REC_DATE);

