CREATE OR REPLACE PROCEDURE SET_AMT(INVIN IN INVOICE.I_NO%TYPE)
AS
    TOTALAMT FLOAT:=0;
    DIS FLOAT:=0;
    FIN FLOAT:=0;
    CURSOR INVI IS SELECT * FROM INVITEM WHERE I_NO=INVIN;
    INVROW INVI%ROWTYPE;
    PRODROW PRODUCT%ROWTYPE;
    PR PRODUCT.PRICE%TYPE;
BEGIN
  OPEN INVI;
  LOOP
    FETCH INVI INTO INVROW;
    IF INVI%NOTFOUND THEN
        EXIT;
    END IF;
    SELECT PRICE INTO PR FROM PRODUCT WHERE PID=INVROW.PID;
    TOTALAMT:=TOTALAMT+INVROW.QTY*PR;
  END LOOP;
  IF TOTALAMT<10 THEN
    DIS:=0.05;
  ELSE
    DIS:=0.2;
  END IF;
  FIN:=TOTALAMT-TOTALAMT*DIS;
  UPDATE INVOICE SET TOTALPRICE=TOTALAMT,DISCOUNT=DIS, FINAMT=FIN WHERE I_NO=INVIN;
END;



DECLARE
    NUM INVOICE.I_NO%TYPE;
BEGIN
    num:='&Enter';
    SET_AMT(num); 
END;