

NOBEL as n
-
laureate_id PK number(3)
NAME  NOT NULL VARCHAR(30)
GENDER CHAR(1) 
CATEGORY CHAR(3)
FIELD VARCHAR(25)
YEAR_AWARD NUMBER(4)
AFF_ROLE VARCHAR(30)
DOB DATE
COUNTRY VARCHAR(10)

EMPLOYEE as e
-
EMP_NO PK string
ENAME VARCHAR(20)
DOB DATE
PINCODE INT
CITY VARCHAR(20)

CUSTOMER as c
-
CUST_NO PK VARCHAR(5)
CNAME VARCHAR(20)
STREET VARCHAR(20)
PINCODE INT
CITY VARCHAR(20) 
DOB DATE
PHONE VARCHAR(11)


PARTS as p
----
PART_NO PK string
PNAME VARCHAR(20)
PRICE INT
QTY INT

# Table documentation comment 1 (try the PDF/RTF export)
ORDERS as o # Table documentation comment 2
------------
ProductID PK int
ORDER_NO PK VARCHAR(5)
CUST_NO VARCHAR(5) FK >- c.CUST_NO 
EMP_NO VARCHAR(5) FK >- e.EMP_NO
ORDERED DATE
SHIPPED DATE
Price money

ORDER_CONTENTS as oc
----
ORDER_NO VARCHAR(5) FK >- o.ORDER_NO
PART_NO VARCHAR(5) FK >- p.PART_NO
QTY INT

CITY VARCHAR(20)

CUSTOMER as c
-
CUST_NO PK VARCHAR(5)
CNAME VARCHAR(20)
STREET VARCHAR(20)
PINCODE INT
CITY VARCHAR(20) 
DOB DATE
PHONE VARCHAR(11)


PARTS as p
----
PART_NO PK string
PNAME VARCHAR(20)
PRICE INT
QTY INT

# Table documentation comment 1 (try the PDF/RTF export)
ORDERS as o # Table documentation comment 2
------------
ProductID PK int
ORDER_NO PK VARCHAR(5)
CUST_NO VARCHAR(5) FK >- c.CUST_NO 
EMP_NO VARCHAR(5) FK >- e.EMP_NO
ORDERED DATE
SHIPPED DATE
Price money

ORDER_CONTENTS as oc
----
ORDER_NO VARCHAR(5) FK >- o.ORDER_NO
PART_NO VARCHAR(5) FK >- p.PART_NO
QTY INT
